version: '2'
services:
  aur-builder:
    build: .
    restart: always
    volumes:
      - "./packagecache:/var/cache/pacman/aurto:rw"
      - "./builddir:/var/lib/aurbuild/:rw"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true
  repo-server:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./packagecache:/usr/share/nginx/html:ro"
